# Generated by Django 3.1.3 on 2023-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('t_no', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20)),
            ],
        ),
    ]
